app = "su-anycable-rails"

[env]
  PORT = 8080
  RAILS_LOG_TO_STDOUT = true
  ANYCABLE_HOST = "::"
  ANYCABLE_PORT = "8081"
  REDIS_HOST = "su-keydb.internal"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[processes]
  rails = "bundle exec puma -C config/puma.rb"
  anycable_rpc = "bundle exec anycable --rpc-host [::]:50051"
  anycable_go = "bin/anycable-go"

[[services]]
  processes = ["rails"]
  internal_port = 8080

  [[services.tcp_checks]]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  processes = ["anycable_go"]
  internal_port = 8081

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8443

  [[services.tcp_checks]]

[[services]]
  processes = ["anycable_rpc"]
  internal_port = 50051

  [[services.tcp_checks]]

[experimental]
  auto_rollback = true
